app/urls.py
from graphene_file_upload.django import FileUploadGraphQLView
from django.views.decorators.csrf import csrf_exempt
from django.urls import path
from . import views
from .schema import schema

app_name = "app"
urlpatterns = [
    path("", views.index, name="index"),
    path("graphql", csrf_exempt(
        FileUploadGraphQLView.as_view(graphiql=True, schema=schema))),

    path('create_image', views.create_image, name="create_image"),

    path("order/<int:order_id>", views.order, name="order"),
    path("create_order", views.create_order, name="create_order"),

    path("product/<int:product_id>", views.product, name="product"),
    path("create_product", views.create_product, name="create_product"),
]

dtsk/urls.py
from django.conf.urls.static import static
from django.urls import path, include
from django.conf import settings
from django.contrib import admin


from app import urls

# Default URLS
urlpatterns = [
    path("admin/", admin.site.urls),

    path("", include(urls))
]


# to show media files in development server
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

app/models.py
from django.db import models
from pathlib import Path
from uuid import uuid4
import os


class Order(models.Model):
    created_at = models.DateTimeField(
        verbose_name="Order Created Date",
        auto_now_add=True
    )

    def __str__(self):
        return f"{self.pk}"


class Product(models.Model):
    name = models.CharField(
        max_length=255,
        verbose_name="Product Name",
        help_text="Enter the name of the product"
    )

    quantity = models.IntegerField(
        default=1,
        verbose_name="Product Quantity",
        help_text="Enter the quantity of the product"
    )

    price = models.DecimalField(
        max_digits=5,
        decimal_places=2,
        verbose_name="Product Price",
        help_text="Enter the price of the product"
    )

    order = models.ForeignKey(
        to=Order,
        null=True,
        blank=True,
        related_name="order",
        verbose_name="Order",
        on_delete=models.SET_NULL,
    )

    def __str__(self):
        return self.name


def get_image_path(instance, filename):
    file_path = Path(filename)
    file_name = str(uuid4()) + file_path.suffix

    return os.path.join('products', file_name)


class Image(models.Model):
    product = models.ForeignKey(
        Product, on_delete=models.CASCADE, related_name="images")
    image = models.ImageField(
        upload_to=get_image_path,
        verbose_name="Product Image",
        help_text="Select the product image"
    )

    def __str__(self):
        return self.image.name

app/forms.py
from django import forms
from .models import Order
from .models import Product
from .models import Image


class ProductForm(forms.ModelForm):
    class Meta:
        model = Product
        fields = ["name", "price", "quantity"]


class OrderForm(forms.ModelForm):
    products = forms.ModelMultipleChoiceField(
        queryset=Product.objects.all(),
        widget=forms.CheckboxSelectMultiple,
        help_text="Select the products for this order"
    )

    class Meta:
        model = Order
        fields = ["products"]


class ImageForm(forms.ModelForm):
    class Meta:
        model = Image
        fields = ["image", "product"]

app/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.http import Http404, HttpResponse
from django.urls import reverse
from .forms import ProductForm
from .forms import OrderForm
from .forms import ImageForm
from .models import Product
from .models import Image
from .models import Order


def index(request):
    products = Product.objects.all()
    orders = Order.objects.all()
    return render(request, 'index.html', {"products": products, "orders": orders})


def product(request, product_id):
    product = get_object_or_404(
        Product.objects.select_related(), pk=product_id)

    return render(request, 'product.html', {"product": product})


def order(request, order_id):
    order = get_object_or_404(Order, pk=order_id)
    products = Product.objects.filter(order=order)

    return render(request, 'order.html', {"products": products})


def create_product(request):

    if request.method == "POST":
        form = ProductForm(request.POST)

        if form.is_valid():
            product = form.save()
            for image in request.FILES.getlist('product-images'):
                product_image = Image(product=product, image=image)
                product_image.save()

            return redirect(reverse('app:product', kwargs={"product_id": product.id}))

    context = {"form": ProductForm()}
    return render(request, 'create_product.html', context)


def create_order(request):

    if request.method == "POST":
        form = OrderForm(request.POST)

        if form.is_valid():
            order = form.save()

            for product_id in dict(form.data).get('products'):
                product = Product.objects.get(pk=product_id)
                product.order = order
                product.save()

            return redirect(reverse('app:order', kwargs={"order_id": order.id}))

    context = {"form": OrderForm()}
    return render(request, 'create_order.html', context)


def create_image(request):
    context = {"form": ImageForm()}
    if request.method == "POST":
        context["form"] = ImageForm(request.POST, request.FILES)
        f = context["form"]
        if f.is_valid():
            f.save()
            return redirect(reverse('app:product', kwargs={"product_id": f.cleaned_data['product'].id}))

    return render(request, 'create_image.html', context)

app/templates/base.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Without GraphQL</title>
  </head>
  <body>
    <header>
      <style>
        .nav li {
          padding: 5px;
        }
      </style>
      <ul class="nav" style="display: flex; list-style-type: none">
        <li><a href="{% url 'app:index' %}">Home </a></li>
        <li><a href="{% url 'app:create_product' %}">Create Product</a></li>
        <li><a href="{% url 'app:create_image' %}">Create Images</a></li>
        <li><a href="{% url 'app:create_order' %}">Create Order</a></li>
      </ul>
    </header>
    <main>{% block content %}{% endblock content %}</main>
  </body>
</html>

app/templates/create_image.html
{% extends "base.html" %} {% block content %}
<main>
  <h1>Create a new product</h1>
  <form action="{% url 'app:create_image' %}" method="post" enctype="multipart/form-data">
    {% csrf_token %}
    <br />
    {{form}}
    <button type="submit">Create</button>
  </form>
</main>
{% endblock content %}

app/templates/create_order.html
{% extends "base.html" %} {% block content %}
<main>
  <h1>Create a new order</h1>
  <form action="{% url 'app:create_order' %}" method="post" enctype="multipart/form-data">
    {% csrf_token %}
    <br />
    {{form}}

    <button type="submit">Create</button>
  </form>
</main>
{% endblock content %}

app/templates/create_product.html
{% extends "base.html" %} {% block content %}
<main>
  <h1>Create a new product</h1>
  <form action="{% url 'app:create_product' %}" method="post" enctype="multipart/form-data">
    {% csrf_token %}
    <br />
    {{form}}

    <div>
      <label for="product-images">Select the product images</label> <br />
      <input type="file" accept="image/*" name="product-images" id="prodcut-images" multiple />
    </div>
    <br />

    <button type="submit">Create</button>
  </form>
</main>
{% endblock content %}

app/templates/detail.html
{% extends "base.html" %} {% block content %}
<main>
  <h1>Name: {{ product.name }}</h1>
  <h2>Price:{{ product.price }}</h2>
  <h3>Quantity:{{ product.quantity}}</h3>
</main>
{% endblock content %}

app/templates/index.html
{% extends "base.html" %} {% block content %}
<main>
  {% if products %}
  <h1>List of Products</h1>
  <ol>
    {% for product in products %}
    <li>
      <h3><a href="{% url 'app:product' product.id %}">{{ product.name }}</a></h3>
    </li>
    {% endfor %}
  </ol>
  {% else %}
  <p>No products are available.</p>
  {% endif %}

  <br />
  <hr />
  {% if orders %}
  <h1>List of Orders</h1>
  <ol>
    {% for order in orders %}
    <li>
      <h4><a href="{% url 'app:order' order.id %}">Click here to view details for order: {{ order.id }}</a></h4>
    </li>
    {% endfor %}
  </ol>
  {% else %}
  <p>No orders are available.</p>
  {% endif %}
</main>
{% endblock content %}

app/templates/order.html
{% extends "base.html" %} {% block content %}
<main>
  {% if products %}
  <h1>This order following products</h1>
  <ol>
    {% for product in products %}
    <li>
      <h3><a href="{% url 'app:product' product.id %}">{{ product.name }}</a></h3>
    </li>
    {% endfor %}
  </ol>
  {% else %}
  <h1>No products are available.</h1>
  {% endif %}
</main>
{% endblock content %}

app/templates/product.html
{% extends "base.html" %} {% block content %}
<main>
  <style>
    .product-image {
      max-height: 300px;
    }
  </style>
  <h1>Name: {{ product.name }}</h1>
  <h2>Price:{{ product.price }}</h2>
  <h3>Quantity:{{ product.quantity}}</h3>

  <hr />
  <h2>Product Images</h2>
  {% for img in product.images.all %}
  <img src="{{ img.image.url }}" alt="picture of {{product.name}}" class="product-image" />
  {%endfor%}
</main>
{% endblock content %}

wgql/templates/product/create.html
{% extends "base.html" %} {% block content %}

<h1>List of the Products</h1>

<form method="post" enctype="multipart/form-data">
  {% csrf_token %} <br />
  {{ form }} <br />

  <label for="product-images">Select the product images</label>
  <input type="file" required="false" type="image" multiple id="product-images" />

  <button type="submit">Create product</button>
</form>

{% endblock content %}

wgql/templates/product/index.html
{% extends "base.html" %} {% block content %}

<h1>List of the Products</h1>

<ul>
  {% for product in products %}
  <li>
    <h2>{{ product.name }}</h2>
    <p>Price: ${{ product.price }}</p>
    <p>Quantity: {{ product.quantity }}</p>
  </li>
  {% empty %}
  <li>No products available.</li>
  {% endfor %}
</ul>

{% endblock content %}